version: '2'

services:
  mongo:
    image: mongo
  letschat:
    image: sdelements/lets-chat
    labels:
      io.rancher.glb: 'true'
  letschat-lb:
    image: rancher/none
    labels:
      io.rancher.glb: 'true'
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.glb.http: 'true'
      io.rancher.container.create_agent: 'true'
